# Generated by Django 5.1.6 on 2025-03-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
                ('nickname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configvalue', models.CharField(max_length=20)),
                ('targetuser', models.ManyToManyField(to='user.user')),
            ],
        ),
    ]
