# Generated by Django 5.1.6 on 2025-03-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11, verbose_name='用户名')),
                ('scheduleContent', models.CharField(max_length=256, verbose_name='事件内容')),
                ('startTime', models.DateTimeField(verbose_name='开始时间')),
                ('endTime', models.DateTimeField(verbose_name='结束时间')),
                ('duration', models.IntegerField(verbose_name='持续时间')),
                ('resource', models.CharField(max_length=256, verbose_name='所需资源')),
            ],
        ),
        migrations.CreateModel(
            name='TeamGroup',
            fields=[
                ('groupID', models.IntegerField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='群ID')),
                ('groupOwner', models.CharField(max_length=11, verbose_name='团队负责人')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.IntegerField(max_length=8, verbose_name='群ID')),
                ('username', models.CharField(max_length=11, verbose_name='成员用户名')),
                ('memberName', models.CharField(max_length=64, verbose_name='成员名')),
                ('permission', models.IntegerField(default=0, verbose_name='权限')),
            ],
        ),
    ]
