# Generated by Django 5.1.6 on 2025-03-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_schedule_teamgroup_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='duration',
        ),
        migrations.AddField(
            model_name='schedule',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='state',
            field=models.IntegerField(default=0, verbose_name='事件状态'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='groupID',
            field=models.IntegerField(verbose_name='群ID'),
        ),
    ]
