# Generated by Django 5.1.6 on 2025-03-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_schedule_duration_schedule_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgroup',
            name='groupName',
            field=models.CharField(default='team', max_length=64, verbose_name='团队名'),
            preserve_default=False,
        ),
    ]
