# Generated by Django 5.1.6 on 2025-03-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_teamgroup_groupdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgroup',
            name='groupID',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='群ID'),
        ),
    ]
