# Generated by Django 5.1.6 on 2025-03-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_teamgroup_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgroup',
            name='groupID',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='群ID'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='groupID',
            field=models.CharField(max_length=8, verbose_name='群ID'),
        ),
    ]
