# Generated by Django 5.1.6 on 2025-03-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_teamgroup_groupid_alter_teammember_groupid'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.CharField(max_length=8, verbose_name='群ID')),
                ('username', models.CharField(max_length=11, verbose_name='用户名')),
                ('scheduleContent', models.CharField(max_length=256, verbose_name='事件内容')),
                ('startTime', models.DateTimeField(verbose_name='开始时间')),
                ('endTime', models.DateTimeField(verbose_name='结束时间')),
                ('resource', models.CharField(max_length=256, verbose_name='所需资源')),
                ('priority', models.IntegerField(default=1)),
                ('state', models.IntegerField(default=0, verbose_name='事件状态')),
            ],
        ),
    ]
