# Generated by Django 5.1.6 on 2025-03-18 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_groupschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupschedule',
            old_name='username',
            new_name='executor',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='username',
            new_name='executor',
        ),
    ]
