# Generated by Django 5.1.6 on 2025-04-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='username',
            field=models.CharField(max_length=11, verbose_name='所属用户'),
        ),
    ]
