# Generated by Django 5.1.6 on 2025-04-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_memo_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11, verbose_name='所属用户')),
                ('timer_type', models.CharField(choices=[('countdown', '倒计时'), ('stopwatch', '正计时'), ('pomodoro', '番茄钟')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(help_text='持续时间(秒)')),
                ('status', models.CharField(choices=[('completed', '已完成'), ('aborted', '已中断')], max_length=10)),
                ('focus_duration', models.PositiveIntegerField(blank=True, help_text='专注时长(分钟)', null=True)),
                ('break_duration', models.PositiveIntegerField(blank=True, help_text='休息时长(分钟)', null=True)),
                ('rounds_completed', models.PositiveIntegerField(blank=True, help_text='完成轮次', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
