# Generated by Django 5.1.6 on 2025-04-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_timerrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11, verbose_name='创建用户')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='标题')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groupID', models.CharField(max_length=8, verbose_name='所属群组')),
            ],
        ),
    ]
