# Generated by Django 5.1.6 on 2025-04-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_teammemo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('username', models.CharField(max_length=11, verbose_name='发布人')),
                ('is_important', models.BooleanField(default=False, verbose_name='重要公告')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
        ),
    ]
