# Generated by Django 5.1.6 on 2025-04-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='groupID',
            field=models.CharField(default='123456789', max_length=8, verbose_name='所属群组'),
            preserve_default=False,
        ),
    ]
