# Generated by Django 5.1.6 on 2025-05-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_announcement_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupschedule',
            name='resource',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='所需资源'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='resource',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='所需资源'),
        ),
    ]
